### ISSUE TITLE
The data extraction script in EB-C7 doesn't working

### ISSUE THREAD

**Issue by lainme** [AMReX-Combustion/PeleC#634]
Commit: 2ee36d716e490388aed7620c5987d3d3abb3c99e (update to date version)

After the simulation of EB-C7 finishes, I tried to use ``pp.py`` to extract the profile, however, the script shows the following error

```
Traceback (most recent call last):
  File "/home/lainme/code/amrex/PeleC/build/Exec/RegTests/EB-C7/tests/eb-c7/pp.py", line 49, in <module>
    srt = np.argsort(ray["x"])
                     ~~~^^^^^
  File "/home/lainme/.local/lib/python3.11/site-packages/yt/data_objects/data_containers.py", line 229, in __getitem__
    f = self._determine_fields([key])[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lainme/.local/lib/python3.11/site-packages/yt/data_objects/data_containers.py", line 1465, in _determine_fields
    finfo = self.ds._get_field_info(field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lainme/.local/lib/python3.11/site-packages/yt/data_objects/static_output.py", line 1009, in _get_field_info
    raise ValueError(
ValueError: The requested field name 'x' is ambiguous and corresponds to any one of the following field types:
 ['boxlib', 'index', 'gas']
Please specify the requested field as an explicit tuple (<ftype>, <fname>).
```

What's the possible reason of the issue? Is this related to the version of yt?

**Comment by marchdf** [comment]
It's getting confused because we added some explicit coordinate fields. Let me fix that. Thank you for reporting!
